/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider, Box, Flex } from "@chakra-ui/react";
import Sidebar from "./components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ChakraProvider>
          <Flex>
            <Box
              width='18%'
              position='fixed'
              top='0'
              left='0'
              height='100vh'
              overflowY='auto'
              bg='white'
            >
              <Sidebar />
            </Box>
            <Box width='82%' marginLeft='18%'>
              {children}
            </Box>
          </Flex>
        </ChakraProvider>
      </body>
    </html>
  );
}
