/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider, Box, Flex } from "@chakra-ui/react";
import Sidebar from "./components/sidebar";
import { ThemeProvider, useTheme } from "./themes/themescontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider>
          <ChakraProvider>
            <Flex>
              <Box
                width='18%'
                position='fixed'
                top='0'
                left='0'
                height='100vh'
                overflowY='auto'
              >
                <Sidebar />
              </Box>
              <Box width='82%' height={"100vh"} marginLeft='18%' bg={"#F4F5F7"}>
                {children}
              </Box>
            </Flex>
          </ChakraProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
